name: Pull Request into Dev

on:
  pull_request:
    branches:
      - "dev"

jobs:
  # First Job
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"

      - name: Install Node modules
        run: yarn install

      - name: Linting
        run: yarn lint

      - name: Unit & Integration tests
        run: yarn test

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.0.6
        id: coverage
        with:
          output: report-markdown
      
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
    
  # Second Job
  build-android:
    needs: install-and-test
    uses: ./.github/workflows/android-build.yml
    with:
      environment: debug
    # secrets: inherit

